### ISSUE TITLE
iOS App Crashes

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#1]
Under iOS 15.3 the app will occasionally crash when

- changing chats
- coming out of suspend
- typing

**Comment by garv-shah** [comment]
yeahhhhh, I didn't realise it was this bad, sorry
will try to pinpoint the issue and fix in the next update

**Comment by garv-shah** [comment]
oh sorry accidental close

**Comment by garv-shah** [comment]
okay, I'm really hoping this (https://github.com/Free-Republic-of-Verdis/verdis-communications/commit/68d621160ea556d642d84b54ee64bc8e1da9f44f) fixes the crashes, though I'm not 100% sure it will, cause the crash reports were extremely hard to understand
I'll close the issue for now, but if it's still crashing frequently, please do feel free to reopen it
