### ISSUE TITLE
Web fails security headers test

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#12]
The website version fails the [security headers](https://securityheaders.com/?q=https%3A%2F%2Fcommunications.vrdgov.org%2F&followRedirects=on) check since it doesn't include the recommended headers.

**Comment by rinchen** [comment]
It also fails Mozilla Observatory for generally the same [reasons](https://observatory.mozilla.org/analyze/communications.vrdgov.org).

**Comment by rinchen** [comment]
And here is the hardenize [report](https://www.hardenize.com/report/communications.vrdgov.org/1643934527) just for reference

**Comment by garv-shah** [comment]
honestly, I don't think it necessarily needs it, cause the security is very tightly managed by the backend, and none of those seem like major issues to me, but ig it might affect seo, so I'll see if I can get to that and add them in if it doesn't break anything

**Comment by garv-shah** [comment]
yeah, this seems like quite a bit of work for something that's not too much of an issue rn
again, feel free to create a pr, but I won't add all the headers myself cause rn, I feel like it's bound to break something
