### ISSUE TITLE
Firebase 404 error

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#13]
When initially loading the website, you get a 404 error.
<img width="1917" alt="Screen Shot 2022-02-03 at 17 23 56 " src="https://user-images.githubusercontent.com/44416/152451569-0e84f581-9482-407c-bf17-aa144af6d504.png">

**Comment by garv-shah** [comment]
yeah, sorry, my bad, I never set up the notifications properly on the web, will get to it

**Comment by garv-shah** [comment]
fixed with https://github.com/Free-Republic-of-Verdis/verdis-communications/commit/bd40befdd2627acc58aa0da0eb0b931626d2f5e2
