### ISSUE TITLE
iOS: Unable to rename group chats

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#3]
Renaming a chat group with no title does not work. The "saving..." spinner will spin and often times the app will crash. The title never gets set.
![IMG_E22E8A8CFF2A-1](https://user-images.githubusercontent.com/44416/152261153-29c137d8-503b-4879-8f85-6a9ce1267282.jpeg)

**Comment by garv-shah** [comment]
yeahhhhhh, I don't know how I broke it, I'll have to check it out when I get time
on an unrelated note, I should probably implement unit testing so stuff like this doesn't happen again, but that's a pain though, so we'll see

**Comment by garv-shah** [comment]
fixed with https://github.com/Free-Republic-of-Verdis/verdis-communications/commit/8bb82841b59838d3c3968def9f04c01dbd317de9
