### ISSUE TITLE
iOS: App shows unread messages but all messages are read

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#7]
There are occasional cases where the app will be badged with an unread messages number but all chats have been read.

**Comment by garv-shah** [comment]
hmm, that's quite odd, the badge number should be automatically managed
I might try and use [this](https://pub.dev/packages/flutter_app_badger) package to manually clear the badge every time the app is opened

**Comment by garv-shah** [comment]
supposedly fixed with https://github.com/Free-Republic-of-Verdis/verdis-communications/commit/8edd6e02ce963189a294ffa98189fd6caae57d3f
