### ISSUE TITLE
iOS Feature: delete chats

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#8]
As a user,
I want to be able to delete (or hide) old chats,
so they do not clutter my view.

**Comment by garv-shah** [comment]
oh, lmao, this was meant to be in this release, it just seems to be very broken
it seems to be somewhat linked to not being able to update group chat names, so I'll have to see what's causing that when I get time

**Comment by garv-shah** [comment]
fixed with https://github.com/Free-Republic-of-Verdis/verdis-communications/commit/8bb82841b59838d3c3968def9f04c01dbd317de9
